/**
 * Email helper using Resend REST API.
 * No SDK needed — a simple fetch is sufficient and keeps bundle size small.
 * Set RESEND_API_KEY and RESEND_FROM_EMAIL in your environment.
 */

import { getPublicSiteOrigin, writersBlockEmailDocument } from "@/infrastructure/email/email-theme"

const RESEND_API_KEY = process.env.RESEND_API_KEY?.trim()
const FROM_EMAIL = process.env.RESEND_FROM_EMAIL || "noreply@writersblock.app"
const APP_NAME = "Writers Block"

function hasResendConfig(): boolean {
  return Boolean(
    RESEND_API_KEY &&
      RESEND_API_KEY.startsWith("re_") &&
      !RESEND_API_KEY.includes("your_resend_api_key")
  )
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;")
}

function safePdfFilename(title: string): string {
  const base =
    title
      .replace(/[<>:"/\\|?*\u0000-\u001f]/g, "_")
      .replace(/\s+/g, "-")
      .slice(0, 80) || "screenplay"
  return `${base}.pdf`
}

interface SendEmailOptions {
  to: string
  subject: string
  html: string
  attachments?: Array<{ filename: string; content: string }>
}

async function sendEmail({ to, subject, html, attachments }: SendEmailOptions): Promise<boolean> {
  if (!hasResendConfig()) {
    console.warn("[email] RESEND_API_KEY is not configured with a real key - skipping email to", to)
    return false
  }

  try {
    const payload: Record<string, unknown> = {
      from: `${APP_NAME} <${FROM_EMAIL}>`,
      to,
      subject,
      html,
    }
    if (attachments?.length) {
      payload.attachments = attachments
    }

    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${RESEND_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
    })

    if (!res.ok) {
      const body = await res.text()
      console.error("[email] Resend error:", res.status, body)
      return false
    }
    return true
  } catch (err) {
    console.error("[email] Failed to send email:", err)
    return false
  }
}

// ── Email templates ──────────────────────────────────────────────────────────

export async function sendAuthOtpEmail(
  email: string,
  code: string,
  purpose: "signup" | "signin" | "password_reset"
): Promise<boolean> {
  const label =
    purpose === "signup"
      ? "signup"
      : purpose === "signin"
        ? "sign-in"
        : "password reset"
  const bodyHtml = `
    <p style="margin:0 0 12px 0;">Use this code to finish ${label} for <strong style="color:#ffffff;">Writers Block</strong>.</p>
    <p style="margin:0 0 20px 0; font-size:14px; color:#00d4ff; word-break:break-all;">${escapeHtml(email)}</p>
    <div style="border-radius:16px; border:1px solid rgba(255,107,53,0.28); background:linear-gradient(135deg, rgba(255,107,53,0.15) 0%, rgba(0,212,255,0.08) 100%); padding:20px 16px; text-align:center;">
      <p style="margin:0 0 10px 0; font-size:11px; text-transform:uppercase; letter-spacing:0.18em; color:rgba(255,255,255,0.5); font-family:ui-monospace,monospace;">${purpose === "signup" ? "Signup" : purpose === "signin" ? "Sign-in" : "Password reset"} code</p>
      <p style="margin:0; font-size:34px; line-height:1; font-weight:800; letter-spacing:0.32em; color:#ffffff; font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace;">${escapeHtml(code)}</p>
    </div>
    <p style="margin:16px 0 0 0; font-size:13px; color:rgba(255,255,255,0.55);">The code expires in 10 minutes. If you requested more than one, use the newest code.</p>`

  if (process.env.NODE_ENV !== "production") {
    console.warn(`[auth-otp] ${purpose} code for ${email}: ${code}`)
  }

  return sendEmail({
    to: email,
    subject:
      purpose === "signup"
        ? "Your Writers Block signup code"
        : purpose === "signin"
          ? "Your Writers Block sign-in code"
          : "Your Writers Block password reset code",
    html: writersBlockEmailDocument({
      preheader: `Your Writers Block ${label} code is ${code}.`,
      title:
        purpose === "signup"
          ? "Your signup code"
          : purpose === "signin"
            ? "Your sign-in code"
            : "Your password reset code",
      bodyHtml,
      footnote: "This code is generated by Writers Block and is not a Supabase verification link.",
    }),
  })
}

export async function sendMasterAdminOtpEmail(email: string, code: string): Promise<boolean> {
  const bodyHtml = `
    <p style="margin:0 0 12px 0;">Use this code to finish <strong style="color:#ffffff;">Master Admin sign-in</strong> for Writers Block.</p>
    <p style="margin:0 0 20px 0; font-size:14px; color:#00d4ff; word-break:break-all;">${escapeHtml(email)}</p>
    <div style="border-radius:16px; border:1px solid rgba(255,107,53,0.28); background:linear-gradient(135deg, rgba(255,107,53,0.15) 0%, rgba(0,212,255,0.08) 100%); padding:20px 16px; text-align:center;">
      <p style="margin:0 0 10px 0; font-size:11px; text-transform:uppercase; letter-spacing:0.18em; color:rgba(255,255,255,0.5); font-family:ui-monospace,monospace;">Master Admin code</p>
      <p style="margin:0; font-size:34px; line-height:1; font-weight:800; letter-spacing:0.32em; color:#ffffff; font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace;">${escapeHtml(code)}</p>
    </div>
    <p style="margin:16px 0 0 0; font-size:13px; color:rgba(255,255,255,0.55);">The code expires in 10 minutes. If you requested more than one, use the newest code.</p>`

  if (process.env.NODE_ENV !== "production") {
    console.warn(`[master-admin-otp] code for ${email}: ${code}`)
  }

  return sendEmail({
    to: email,
    subject: "Your Writers Block Master Admin code",
    html: writersBlockEmailDocument({
      preheader: `Your Writers Block Master Admin code is ${code}.`,
      title: "Your Master Admin code",
      bodyHtml,
      footnote: "This code is generated by Writers Block for Master Admin sign-in only.",
    }),
  })
}

export async function sendPaymentConfirmation(
  email: string,
  plan: string,
  amountPaise: number,
  expiryDate: Date,
  billingCycle: "monthly" | "annual"
): Promise<void> {
  const site = getPublicSiteOrigin()
  const amount = `₹${(amountPaise / 100).toLocaleString("en-IN")}`
  const planDisplay = plan.charAt(0).toUpperCase() + plan.slice(1)
  const cycleDisplay = billingCycle === "annual" ? "Annual" : "Monthly"
  const expiry = expiryDate.toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  })

  const bodyHtml = `
    <p style="margin:0 0 16px 0;">Thank you for subscribing! Your <strong style="color:#ffffff;">${escapeHtml(planDisplay)}</strong> plan is now active.</p>
    <table role="presentation" width="100%" style="border-collapse:collapse; margin:0; font-size:14px;">
      <tr>
        <td style="padding:10px 0; color:rgba(255,255,255,0.55); border-bottom:1px solid rgba(255,255,255,0.08);">Plan</td>
        <td style="padding:10px 0; text-align:right; font-weight:600; color:#ffffff; border-bottom:1px solid rgba(255,255,255,0.08);">${escapeHtml(planDisplay)} (${escapeHtml(cycleDisplay)})</td>
      </tr>
      <tr>
        <td style="padding:10px 0; color:rgba(255,255,255,0.55); border-bottom:1px solid rgba(255,255,255,0.08);">Amount paid</td>
        <td style="padding:10px 0; text-align:right; color:#e8e8e6; border-bottom:1px solid rgba(255,255,255,0.08);">${amount}</td>
      </tr>
      <tr>
        <td style="padding:10px 0; color:rgba(255,255,255,0.55);">Valid until</td>
        <td style="padding:10px 0; text-align:right; color:#e8e8e6;">${escapeHtml(expiry)}</td>
      </tr>
    </table>`

  await sendEmail({
    to: email,
    subject: `Payment Confirmed — ${planDisplay} Plan Activated`,
    html: writersBlockEmailDocument({
      preheader: `Your ${planDisplay} plan is active.`,
      title: "Payment confirmed",
      bodyHtml,
      primaryCta: { href: `${site}/dashboard`, label: "Go to dashboard" },
      footnote: "If you have billing questions, reply to this email.",
    }),
  })
}

export async function sendExpiryWarning(
  email: string,
  plan: string,
  daysLeft: number,
  expiryDate: Date
): Promise<void> {
  const site = getPublicSiteOrigin()
  const planDisplay = plan.charAt(0).toUpperCase() + plan.slice(1)
  const expiry = expiryDate.toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  })

  const bodyHtml = `
    <p style="margin:0 0 16px 0;">Your <strong style="color:#ffffff;">${escapeHtml(planDisplay)}</strong> plan will expire on <strong style="color:#00d4ff;">${escapeHtml(expiry)}</strong> (${daysLeft} day${daysLeft !== 1 ? "s" : ""} left).</p>
    <p style="margin:0; color:rgba(255,255,255,0.7);">Renew to keep full access to your screenplays and AI tools.</p>`

  await sendEmail({
    to: email,
    subject: `Your ${planDisplay} Plan expires in ${daysLeft} day${daysLeft !== 1 ? "s" : ""}`,
    html: writersBlockEmailDocument({
      preheader: `Your subscription ends in ${daysLeft} day${daysLeft !== 1 ? "s" : ""}.`,
      title: "Subscription expiring soon",
      bodyHtml,
      primaryCta: { href: `${site}/dashboard/subscription`, label: "Renew subscription" },
      footnote: "After expiry, your account moves to the free plan (limited projects and AI).",
    }),
  })
}

/** Email screenplay PDF (Resend attachment) to the user's registered address. */
export async function sendScreenplayPdfEmail(
  email: string,
  screenplayTitle: string,
  pdfBuffer: Buffer
): Promise<boolean> {
  const displayTitle = screenplayTitle.trim().slice(0, 200) || "Your screenplay"
  const filename = safePdfFilename(displayTitle)
  const site = getPublicSiteOrigin()
  const host = site.replace(/^https?:\/\//, "")

  return sendEmail({
    to: email,
    subject: `Your screenplay: ${displayTitle}`,
    html: writersBlockEmailDocument({
      preheader: "Your PDF is attached.",
      title: "Your screenplay PDF is attached",
      bodyHtml: `
        <p style="margin:0 0 12px 0;">Here is <strong style="color:#ffffff;">${escapeHtml(displayTitle)}</strong> in PDF — same template as the editor.</p>
        <p style="margin:0; font-size:14px; color:rgba(255,255,255,0.5);">If you don&apos;t see the attachment, check your spam folder.</p>`,
      primaryCta: { href: `${site}/editor`, label: "Open editor" },
      footnote: `Sent to your registered address · ${escapeHtml(host)}`,
    }),
    attachments: [{ filename, content: pdfBuffer.toString("base64") }],
  })
}

export async function sendOrgInviteEmail(params: {
  email: string
  orgName: string
  inviterEmail: string | null
  acceptUrl: string
  role: string
  expiresAt: string
}): Promise<boolean> {
  const expiry = new Date(params.expiresAt).toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  })
  const bodyHtml = `
    <p style="margin:0 0 12px 0;">You have been invited to join <strong style="color:#ffffff;">${escapeHtml(params.orgName)}</strong> on Writers Block.</p>
    <table role="presentation" width="100%" style="border-collapse:collapse; margin:0 0 16px 0; font-size:14px;">
      <tr>
        <td style="padding:8px 0; color:rgba(255,255,255,0.55); border-bottom:1px solid rgba(255,255,255,0.08);">Role</td>
        <td style="padding:8px 0; text-align:right; font-weight:600; color:#ffffff; border-bottom:1px solid rgba(255,255,255,0.08);">${escapeHtml(params.role)}</td>
      </tr>
      <tr>
        <td style="padding:8px 0; color:rgba(255,255,255,0.55);">Expires</td>
        <td style="padding:8px 0; text-align:right; color:#e8e8e6;">${escapeHtml(expiry)}</td>
      </tr>
    </table>
    <p style="margin:0; font-size:13px; color:rgba(255,255,255,0.55);">Accept this invite using the same email address: ${escapeHtml(params.email)}.</p>`

  return sendEmail({
    to: params.email,
    subject: `Invitation to ${params.orgName}`,
    html: writersBlockEmailDocument({
      preheader: `Join ${params.orgName} on Writers Block.`,
      title: "Organization invitation",
      bodyHtml,
      primaryCta: { href: params.acceptUrl, label: "Accept invitation" },
      footnote: params.inviterEmail
        ? `Invited by ${escapeHtml(params.inviterEmail)}. If you were not expecting this invite, ignore this email.`
        : "If you were not expecting this invite, ignore this email.",
    }),
  })
}
